ARG prefectVersion
ARG pythonVersion

FROM prefecthq/prefect:${prefectVersion}-python${pythonVersion}

# Add our flow code to the image
COPY flows /opt/prefect/flows

# Run our flow script when the container starts
CMD ["python", "flows/critical_flow.py"]